- name: Create private key
  ansible.builtin.copy:
    content: "{{ rhpds_ctf_participants_ar_ssh_private_key }}"
    dest: /home/{{ rhpds_ctf_participants_ar_username }}/.ssh/rhpds_ctf_participants_ar_ssh_private_key
    owner: "{{ rhpds_ctf_participants_ar_username }}"
    group: "{{ rhpds_ctf_participants_ar_group }}"
    mode: 0600
